version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: /run/secrets/mariadb_user
      MARIADB_PASSWORD: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD: /run/secrets/mariadb_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress-network
    ports:
      - "3306:3306"
    secrets:
      - mariadb_root_password
      - mariadb_password
      - mariadb_user
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  wordpress:
    image: wordpress:6.3.2-php8.0-apache
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: /run/secrets/mariadb_user
      WORDPRESS_DB_PASSWORD: /run/secrets/mariadb_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-network
    secrets:
      - mariadb_user
      - mariadb_password

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress-network:
    driver: bridge

secrets:
  mariadb_user:
    file: secrets/mariadb_user.txt
  mariadb_password:
    file: secrets/mariadb_password.txt
  mariadb_root_password:
    file: secrets/mariadb_root_password.txt
