version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: /run/secrets/mariadb-user
      MARIADB_PASSWORD: /run/secrets/mariadb-password
      MARIADB_ROOT_PASSWORD: /run/secrets/mariadb-root-password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - wordpress-network
    ports:
      - "3306:3306"
    secrets:
      - mariadb-root-password
      - mariadb-password
      - mariadb-user
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  wordpress:
    image: wordpress:6.3.2-php8.0-apache
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: /run/secrets/mariadb-user
      WORDPRESS_DB_PASSWORD: /run/secrets/mariadb-password
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
    secrets:
      - mariadb-user
      - mariadb-password

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local

networks:
  wordpress-network:
    driver: bridge

secrets:
  mariadb-user:
    file: secrets/mariadb-user.txt
  mariadb-password:
    file: secrets/mariadb-password.txt
  mariadb-root-password:
    file: secrets/mariadb-root-password.txt
