apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.kompose.network/2026-s7-esiea-devops-cicd-tp1-wordpress-net: "true"
    io.kompose.service: mariadb
    kompose.cmd: kompose convert -f docker-compose.yml -o PaulineSoubrieWordpress/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        io.kompose.network/2026-s7-esiea-devops-cicd-tp1-wordpress-net: "true"
        io.kompose.service: mariadb
        kompose.cmd: kompose convert -f docker-compose.yml -o PaulineSoubrieWordpress/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
            - name: MARIADB_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
            - name: MARIADB_USER
          image: mariadb:10.5
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
